export const SET_INFO_BOOKING_ROOM = "SET_INFO_BOOKING_ROOM";

export const SET_SELECTED_SEAT = "SET_SELECTED_SEAT";

export const SET_DELETED_SEAT = "SET_DELETED_SEAT";

export const SET_CLEAR_SEAT_LIST = "SET_CLEAR_SEAT_LIST";